// Generated by CoffeeScript 1.6.3
var NumberModel, Text0, Text01, Text02, Text03, Text04, Text05, baseModel;

baseModel = {
  id: String,
  val: String,
  get: function() {
    return this.val;
  },
  set: function(value) {
    this.val = value;
    return this.ref();
  },
  ref: function() {
    return $(this.id).val(this.val);
  },
  eff: function() {
    return this.val = $(this.id).val();
  },
  clear: function() {
    return this.set('');
  }
};

NumberModel = {
  __proto__: baseModel,
  val: Number,
  set: function(value) {
    this.val = typeof value === 'string' ? Number(value) : value;
    this.ref();
  }
};

Text0 = {
  id: '#Header_Number',
  __proto__: NumberModel
};

Text01 = {
  id: '#Header_Text01',
  val: Number,
  __proto__: baseModel
};

Text02 = {
  id: '#Header_Text02',
  val: Number,
  __proto__: baseModel
};

Text03 = {
  id: '#Header_Text03',
  val: Number,
  __proto__: baseModel
};

Text04 = {
  id: '#Header_Text04',
  val: String,
  __proto__: baseModel
};

Text05 = {
  id: '#Header_Text05',
  val: Date,
  __proto__: baseModel
};

$(function() {
  Text01.val = "あいうえお";
  Text01.ref();
  Text05.val = new Date();
  return Text05.ref();
});
