// Generated by CoffeeScript 1.6.3
var Text01, Text02, Text03, Text04, Text05, model;

model = {
  id: String,
  val: String,
  get: function() {
    return this.val;
  },
  set: function(value) {
    return this.val = value;
  },
  ref: function() {
    return $(this.id).val(this.val);
  },
  clear: function() {
    return this.val = "";
  }
};

Text01 = {
  id: '#Header_Text01',
  val: Number,
  __proto__: model
};

Text02 = {
  id: '#Header_Text02',
  val: Number,
  __proto__: model
};

Text03 = {
  id: '#Header_Text03',
  val: Number,
  __proto__: model
};

Text04 = {
  id: '#Header_Text04',
  val: String,
  __proto__: model
};

Text05 = {
  id: '#Header_Text05',
  val: Date,
  __proto__: model
};

$(function() {
  Text01.val = "あいうえお";
  Text01.ref();
  Text05.val = new Date();
  return Text05.ref();
});
